/*
 * Swagger Calculation
 * This is a sample server Calculation server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eu.eisti.calculation.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CalculationResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-06T15:03:26.123+01:00")
public class CalculationResponse {
  @JsonProperty("resultat")
  private Long resultat = null;

  public CalculationResponse resultat(Long resultat) {
    this.resultat = resultat;
    return this;
  }

   /**
   * Get resultat
   * @return resultat
  **/
  @ApiModelProperty(value = "")
  public Long getResultat() {
    return resultat;
  }

  public void setResultat(Long resultat) {
    this.resultat = resultat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CalculationResponse calculationResponse = (CalculationResponse) o;
    return Objects.equals(this.resultat, calculationResponse.resultat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CalculationResponse {\n");
    
    sb.append("    resultat: ").append(toIndentedString(resultat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

