/*
 * Swagger Calculation
 * This is a sample server Calculation server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eu.eisti.calculation.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CalculationResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-06T16:23:24.779+01:00")
public class CalculationResponse {
  @JsonProperty("instanmonth")
  private Long instanmonth = null;

  @JsonProperty("totalcost")
  private Long totalcost = null;

  public CalculationResponse instanmonth(Long instanmonth) {
    this.instanmonth = instanmonth;
    return this;
  }

   /**
   * Get instanmonth
   * @return instanmonth
  **/
  @ApiModelProperty(value = "")
  public Long getInstanmonth() {
    return instanmonth;
  }

  public void setInstanmonth(Long instanmonth) {
    this.instanmonth = instanmonth;
  }

  public CalculationResponse totalcost(Long totalcost) {
    this.totalcost = totalcost;
    return this;
  }

   /**
   * Get totalcost
   * @return totalcost
  **/
  @ApiModelProperty(value = "")
  public Long getTotalcost() {
    return totalcost;
  }

  public void setTotalcost(Long totalcost) {
    this.totalcost = totalcost;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CalculationResponse calculationResponse = (CalculationResponse) o;
    return Objects.equals(this.instanmonth, calculationResponse.instanmonth) &&
        Objects.equals(this.totalcost, calculationResponse.totalcost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instanmonth, totalcost);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CalculationResponse {\n");
    
    sb.append("    instanmonth: ").append(toIndentedString(instanmonth)).append("\n");
    sb.append("    totalcost: ").append(toIndentedString(totalcost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

